format_version: 10
pipelines:
  testpipeline:
    group: mygroup
    materials:
      mygit:
        git: https://github.com/MattLishmanCtM/gocd-test
    stages:
      - test:
          jobs:
            list-files:
              tasks:
                - exec:
                    command: ls
            print-directory:
              tasks:
                - exec:
                    command: pwd
            docker-stuff:
              tasks:
                - exec:
                    command: docker
                    arguments:
                      - -v
