format_version: 10
pipelines:
  testpipeline:
    group: mygroup
    materials:
      mygit:
        git: https://github.com/MattLishmanCtM/gocd-test
        destination: app
    stages:
      - test:
          jobs:
            install:
              tasks:
                - exec:
                    command: pwd
                - exec:
                    command: docker
                    arguments:
                      - > 
                        run node:16
                        node -v
                - exec:
                    command: docker
                    arguments:
                      - run
                      - -v $(pwd)/app:/app
                      - node:16
                      - npm install
