format_version: 10
pipelines:
  testpipeline:
    group: mygroup
    materials:
      mygit:
        git: https://github.com/MattLishmanCtM/gocd-test
        destination: app
    stages:
      - test:
          jobs:
            install:
              tasks:
                - exec:
                    command: docker run -v $(pwd)/app:/app node
                    arguments:
                      - node -v
                - exec:
                    command: docker run -v $(pwd)/app:/app node
                    arguments:
                      - npm install
